<?php
/**
 * Plugin Name: Surtilec — WhatsApp Lead Source
 * Description: Marks WhatsApp conversations from the site as Surtilec leads, even when the number is shared with Grupo Gerson.
 * Version:     0.1.0
 * Author:      Surtilec
 *
 * @package Surtilec
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const SURTILEC_WHATSAPP_NUMBER_OLD     = '573204499026';
const SURTILEC_WHATSAPP_NUMBER         = '573219932050';
const SURTILEC_WHATSAPP_TEL            = '+573219932050';
const SURTILEC_WHATSAPP_DISPLAY        = '+57 321 993 2050';
const SURTILEC_WHATSAPP_DISPLAY_OLD    = '+57 320 449 9026';
const SURTILEC_WHATSAPP_DISPLAY_SHORT  = '321 993 2050';
const SURTILEC_WHATSAPP_DISPLAY_SHORT_OLD = '320 449 9026';

/**
 * Force the floating Joinchat message to identify the lead source.
 *
 * @param array $settings Joinchat settings.
 * @return array
 */
add_filter( 'joinchat_settings', 'surtilec_whatsapp_source_joinchat_settings', 50 );
function surtilec_whatsapp_source_joinchat_settings( $settings ) {
	$settings['telephone'] = SURTILEC_WHATSAPP_NUMBER;

	if ( function_exists( 'is_product' ) && is_product() ) {
		$settings['message_send'] = 'Hola Surtilec, vengo desde surtilec.com y quiero cotizar: {PRODUCT}. Página: {URL}';
		return $settings;
	}

	$settings['message_send'] = 'Hola Surtilec, vengo desde surtilec.com y quiero una cotización. Página: {URL}';
	return $settings;
}

/**
 * Replace the previous shared number in rendered HTML.
 *
 * Some phone/WhatsApp links are generated by child-theme files that currently
 * have local unrelated changes. This output buffer keeps production correct
 * without deploying the whole child theme.
 */
add_action( 'template_redirect', 'surtilec_whatsapp_source_start_buffer', 0 );
function surtilec_whatsapp_source_start_buffer() {
	if ( is_admin() || wp_doing_ajax() || is_feed() || is_robots() || is_trackback() ) {
		return;
	}

	if ( function_exists( 'wp_is_json_request' ) && wp_is_json_request() ) {
		return;
	}

	ob_start( 'surtilec_whatsapp_source_replace_numbers' );
}

/**
 * Replace stale phone literals with the current shared number.
 *
 * @param string $html Rendered HTML.
 * @return string
 */
function surtilec_whatsapp_source_replace_numbers( $html ) {
	$html = strtr(
		$html,
		array(
			SURTILEC_WHATSAPP_NUMBER_OLD         => SURTILEC_WHATSAPP_NUMBER,
			'+573204499026'                     => SURTILEC_WHATSAPP_TEL,
			SURTILEC_WHATSAPP_DISPLAY_OLD       => SURTILEC_WHATSAPP_DISPLAY,
			SURTILEC_WHATSAPP_DISPLAY_SHORT_OLD => SURTILEC_WHATSAPP_DISPLAY_SHORT,
		)
	);

	$old_default = rawurlencode( 'Hola Surtilec, quiero una cotización.' );
	$new_default = rawurlencode(
		'Hola Surtilec, vengo desde surtilec.com y quiero una cotización. Página: '
		. surtilec_whatsapp_source_current_url()
	);

	return str_replace( '?text=' . $old_default, '?text=' . $new_default, $html );
}

/**
 * Current public URL without transient cache-busting query strings.
 *
 * @return string
 */
function surtilec_whatsapp_source_current_url() {
	$request_uri = isset( $_SERVER['REQUEST_URI'] ) ? wp_unslash( $_SERVER['REQUEST_URI'] ) : '/';
	$path        = strtok( $request_uri, '?' );

	return home_url( $path ? $path : '/' );
}

/**
 * Normalize hardcoded wa.me links generated by templates.
 *
 * The child theme already prefixes messages with "Hola Surtilec"; this adds a
 * consistent source line so the sales team can distinguish Surtilec leads from
 * Grupo Gerson conversations on a shared WhatsApp number.
 */
add_action( 'wp_footer', 'surtilec_whatsapp_source_script', 50 );
function surtilec_whatsapp_source_script() {
	if ( is_admin() ) {
		return;
	}

	$config = array(
		'number'    => SURTILEC_WHATSAPP_NUMBER,
		'oldNumber' => SURTILEC_WHATSAPP_NUMBER_OLD,
		'fallback'  => 'Hola Surtilec, vengo desde surtilec.com y quiero una cotización.',
		'source'    => 'Origen: Surtilec.com',
		'page'      => 'Página:',
	);
	?>
	<script>
	(function () {
		var cfg = <?php echo wp_json_encode( $config, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ); ?>;
		var selector = 'a[href*="wa.me/' + cfg.number + '"],a[href*="wa.me/' + cfg.oldNumber + '"],a[href*="api.whatsapp.com/send"]';
		document.querySelectorAll(selector).forEach(function (link) {
			try {
				var url = new URL(link.href);
				var phone = url.searchParams.get('phone') || url.pathname.replace(/\D/g, '');
				if (phone && phone.indexOf(cfg.number) === -1 && phone.indexOf(cfg.oldNumber) === -1) {
					return;
				}
				if (url.hostname.indexOf('wa.me') !== -1) {
					url.pathname = '/' + cfg.number;
				}
				if (url.searchParams.has('phone')) {
					url.searchParams.set('phone', cfg.number);
				}

				var text = url.searchParams.get('text') || cfg.fallback;
				if (!/surtilec\.com/i.test(text)) {
					text += "\n\n" + cfg.source;
				}
				if (!/(P[aá]gina):/i.test(text)) {
					text += "\n" + cfg.page + " " + window.location.href;
				}

				url.searchParams.set('text', text);
				link.href = url.toString();
			} catch (err) {}
		});
	})();
	</script>
	<?php
}
